### ISSUE TITLE
Crashing displaying certain tensor shapes

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#294]
Somehow this must be a user error but I don't know what it is. My code appears to be fully up-to-date and yet I get a crash displaying certain tensors. After a lot of time debugging my gabor code I decided to create a small app and sure enough it also shows the problem. The sample app is "tensorbug" in emer/auditory/tensorbug.

**Comment by rohrlich** [comment]
Note that the sample app is not dependent on any auditory code it is just where I was working. Here is the stacktrace you get when trying to display Btensor

rohrlich@MacBook-Pro-4:tensorbug:> ./tensorbug 
OpenGL version 4.1 ATI-2.11.20
panic: runtime error: index out of range

goroutine 24 [running]:
github.com/emer/etable/etensor.(*Float32).FloatVal(0x5f4b198, 0xc003381830, 0x5, 0x5, 0x400ed2f)
	/Users/rohrlich/go/src/github.com/emer/etable/etensor/numeric.gen.go:2411 +0x80
github.com/emer/etable/etensor.Prjn2DVal(0x50c3900, 0x5f4b198, 0x0, 0xb, 0x0, 0xb)
	/Users/rohrlich/go/src/github.com/emer/etable/etensor/prjn2d.go:142 +0x77e
github.com/emer/etable/etview.(*TensorView).UpdateSliceGrid(0xc0000bf100)
	/Users/rohrlich/go/src/github.com/emer/etable/etview/tensorview.go:435 +0x283
github.com/goki/gi/giv.(*SliceViewBase).Render2D(0xc0000bf100)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewbase.go:837 +0x185
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc000285700)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1138 +0xb9
github.com/goki/gi/gi.(*Frame).Render2D(0xc000285700)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/frame.go:169 +0xce
github.com/goki/gi/gi.(*Node2DBase).Render2DChildren(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:749 +0xa2
github.com/goki/gi/gi.(*Viewport2D).Render2D(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:491 +0x6d
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:710 +0x82
github.com/goki/gi/gi.(*Node2DBase).FullRender2DTree(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:593 +0x89
github.com/goki/gi/gi.(*Viewport2D).FullRender2DTree(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:434 +0x85
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:653 +0x336
github.com/goki/gi/gi.(*Viewport2D).SetNeedsFullRender(0xc0005a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:617 +0x4f
github.com/goki/gi/gi.(*Window).FullReRender(0xc00054c000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:919 +0x5e
github.com/goki/gi/gi.(*Window).Resized(0xc00054c000, 0x66c, 0x380)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:653 +0x2da
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc00054c000, 0x5094280, 0xc000598480)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1492 +0x2ac
github.com/goki/gi/gi.(*Window).EventLoop(0xc00054c000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1448 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:817 +0x94

**Comment by rohrlich** [comment]
I'll go ahead and fix this.

**Comment by rohrlich** [comment]
Filed against the wrong package but it is fixed :)
