### ISSUE TITLE
Selecting "Debug" from menu leads to runtime error

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#357]
2020/02/08 09:21:01 Gi Debug: File type Csv not supported
panic: runtime error: index out of range [0] with length 0

goroutine 38 [running]:
github.com/goki/gi/gi.(*Layout).LayoutGrid(0xc011617600)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:833 +0x5f8
github.com/goki/gi/gi.(*Layout).Layout2D(0xc011617600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x41d0000000000000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1725 +0x23a
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0xc011617080, 0x0, 0x9)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:817 +0x167
github.com/goki/gi/gi.(*Layout).Layout2D(0xc011617080, 0x9, 0x9, 0xffffffffffffffdd, 0xffffffffffffffdd, 0x0, 0x41d00000411c0000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1734 +0xca
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0xc011616580, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:817 +0x167

**Comment by rohrlich** [comment]
Fixed sort of. Closing and will pick up over in gide/issues.
