### ISSUE TITLE
Segfault when closing open file prompt

### ISSUE THREAD

**Issue by hoehtd** [goki/gi#388]
Error code:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12d71c2]

goroutine 28 [running]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetMonitor.func1(0x0, 0x0)
	/home/theo/Projects/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:661 +0x22
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetMonitor(0x0, 0x19e6540)
	/home/theo/Projects/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:661 +0x2f
github.com/goki/gi/oswin/driver/glos.(*windowImpl).getScreen(0xc000452900, 0x4)
	/home/theo/Projects/go/src/github.com/goki/gi/oswin/driver/glos/window.go:588 +0x6d
github.com/goki/gi/oswin/driver/glos.(*windowImpl).Screen(0xc000452900, 0x9)
	/home/theo/Projects/go/src/github.com/goki/gi/oswin/driver/glos/window.go:356 +0x2b
github.com/goki/gi/gi.(*WindowGeomPrefs).RecordPref(0x309ddb8, 0xc025cd1000)
	/home/theo/Projects/go/src/github.com/goki/gi/gi/wingeom.go:249 +0x1e9
github.com/goki/gi/gi.(*Window).HiPriorityEvents(0xc025cd1000, 0x19483a0, 0xc023342000, 0x1)
	/home/theo/Projects/go/src/github.com/goki/gi/gi/window.go:1673 +0x381
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc025cd1000, 0x19483a0, 0xc023342000)
	/home/theo/Projects/go/src/github.com/goki/gi/gi/window.go:1504 +0x2c7
github.com/goki/gi/gi.(*Window).EventLoop(0xc025cd1000)
	/home/theo/Projects/go/src/github.com/goki/gi/gi/window.go:1448 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/home/theo/Projects/go/src/github.com/goki/gi/gi/window.go:863 +0xa6
```
System: Ubuntu 18.04
Go version: 1.13.8

I encountered this error once when trying to load saved weights of an emergent network. Cannot replicate the error afterwards. I am using only one monitor although I was screen sharing with Zoom when the error occurred.

**Comment by rcoreilly** [comment]
w.glw is nil -- added a nil guard so won't crash in future.
