### ISSUE TITLE
TextField typing while updating in other process: crash

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#396]
cd /Users/oreilly/ccngit/bg/sims/bgate (from: {FileDirPath})
panic: runtime error: slice bounds out of range [3:1]

goroutine 50 [running]:
github.com/goki/gi/gi.(*TextField).InsertAtCursor(0xc00021aa00, 0x62b55c1, 0x1)
	/Users/oreilly/go/src/github.com/goki/gi/gi/textfield.go:622 +0x489
github.com/goki/gi/gi.(*TextField).KeyInput(0xc00021aa00, 0xc014c06690)
	/Users/oreilly/go/src/github.com/goki/gi/gi/textfield.go:1226 +0x1ca
github.com/goki/gi/gi.(*TextField).KeyChordEvent.func1(0x5512f40, 0xc00021aa00, 0x5513fc0, 0xc000deb000, 0x7, 0x50fe7e0, 0xc014c06690)
	/Users/oreilly/go/src/github.com/goki/gi/gi/textfield.go:1326 +0x8a
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc00560bd28, 0x5513fc0, 0xc000deb000, 0x7, 0x50fe7e0, 0xc014c06690)
	/Users/oreilly/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000deb198, 0x54bb1a0, 0xc014c06690, 0x1)
	/Users/oreilly/go/src/github.com/goki/gi/gi/events.go:225 +0x39a
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000deb000, 0x54bb1a0, 0xc014c06690)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1534 +0x8d1
github.com/goki/gi/gi.(*Window).EventLoop(0xc000deb000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1456 +0x36
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000deb000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:854 +0x6d
main.mainrun()
	/Users/oreilly/ccngit/bg/sims/bgate/bgate.go:1060 +0x6b
main.main.func1()
	/Users/oreilly/ccngit/bg/sims/bgate/bgate.go:40 +0x20
github.com/goki/gi/gimain.Main.func1(0x54cfc00, 0x6946800)
	/Users/oreilly/go/src/github.com/goki/gi/gimain/gimain.go:31 +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1()
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/glos/app.go:87 +0x40
created by github.com/goki/gi/oswin/driver/glos.Main
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/glos/app.go:86 +0x87

/Users/oreilly/ccngit/bg/sims/bgate/bgate <b>failed</b> at: Fri Jul  10 18:05:33 PDT 2020 with error: exit status 2

**Comment by rcoreilly** [comment]
also all fixed in v2 :)
