### ISSUE TITLE
glgpu crash

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#406]
durring massive 3d obj render -- got to epoch 42, trial 50..

```
SIGABRT: abort
PC=0x7fff6b33f33a m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4e54e60, 0xc008b99920, 0xc008b99980)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc008b998f0 sp=0xc008b998b8 pc=0x4005e0b
github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowBufferSubData(0x7fff3b04291a, 0xc000008a11, 0x0, 0x40, 0xc027f7cf00)
	_cgo_gotypes.go:3574 +0x45 fp=0xc008b99920 sp=0xc008b998f0 pc=0x4dec265
github.com/go-gl/gl/v3.3-core/gl.BufferSubData.func1(0x8a11, 0x0, 0x40, 0xc027f7cf00)
	/Users/oreilly/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:8644 +0x7f fp=0xc008b99960 sp=0xc008b99920 pc=0x4e0df8f
github.com/go-gl/gl/v3.3-core/gl.BufferSubData(0x8a11, 0x0, 0x40, 0xc027f7cf00)
	/Users/oreilly/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:8644 +0x47 fp=0xc008b99990 sp=0xc008b99960 pc=0x4df0b27
github.com/goki/gi/oswin/driver/internal/glgpu.(*Uniform).SetValueImpl(0xc000a997a0, 0x4f9a780, 0xc027f7ce40, 0x400d2b2, 0xc027f7ce40)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/internal/glgpu/uniforms.go:202 +0x26b5 fp=0xc008b99b18 sp=0xc008b99990 pc=0x4e26565
github.com/goki/gi/oswin/driver/internal/glgpu.(*Uniform).SetValue(0xc000a997a0, 0x4f9a780, 0xc027f7ce40, 0xc027f7ce40, 0xc000a997a0)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/internal/glgpu/uniforms.go:102 +0x43 fp=0xc008b99b70 sp=0xc008b99b18 pc=0x4e23e23
github.com/goki/gi/gi3d.(*Renderers).SetMatrix(0xc000c62768, 0xc003b5f568)
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/render.go:79 +0xfb fp=0xc008b99bd8 sp=0xc008b99b70 pc=0x4daf64b
github.com/goki/gi/gi3d.(*Solid).Render3D(0xc003b5f400, 0xc000c62000, 0x1, 0x54251c0, 0xc000760500)
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/solid.go:206 +0xb6 fp=0xc008b99c10 sp=0xc008b99bd8 pc=0x4dbc386
github.com/goki/gi/gi3d.(*Scene).Render3D(0xc000c62000, 0xc000c62001)
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/scene.go:1240 +0x36e fp=0xc008b99e30 sp=0xc008b99c10 pc=0x4db8a5e
github.com/goki/gi/gi3d.(*Scene).RenderOffFrame.func1()
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/scene.go:1105 +0x50 fp=0xc008b99e58 sp=0xc008b99e30 pc=0x4dc7530
github.com/goki/gi/oswin/driver/glos.(*appImpl).mainLoop(0x6826320)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/glos/app.go:167 +0x188 fp=0xc008b99f30 sp=0xc008b99e58 pc=0x4e2aad8
github.com/goki/gi/oswin/driver/glos.Main(0xc00051ae70)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/glos/app.go:90 +0x97 fp=0xc008b99f50 sp=0xc008b99f30 pc=0x4e2a5c7
github.com/goki/gi/oswin/driver.driverMain(...)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/driver_glos.go:18
github.com/goki/gi/oswin/driver.Main(...)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/driver.go:27
github.com/goki/gi/gimain.Main(0x524a490)
	/Users/oreilly/go/src/github.com/goki/gi/gimain/gimain.go:30 +0x57 fp=0xc008b99f70 sp=0xc008b99f50 pc=0x4e3c607
main.main()
	/Users/oreilly/go/src/github.com/emer/envs/obj3dsac/main.go:20 +0x2d fp=0xc008b99f88 sp=0xc008b99f70 pc=0x4e4754d
runtime.main()
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:203 +0x212 fp=0xc008b99fe0 sp=0xc008b99f88 pc=0x4038b22
runtime.goexit()
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc008b99fe8 sp=0xc008b99fe0
```

**Comment by rcoreilly** [comment]
Epc: 42 	 Trial: 50 	 Opening object: /Users/oreilly/ccn_images/CU3D_100_plus_models_obj/blade/blade_014.obj

**Comment by rcoreilly** [comment]
another one: 
```
Epc: 42 	 Trial: 25 	 Opening object: /Users/oreilly/ccn_images/CU3D_100_plus_models_obj/car/car_hatchback_002.obj
SIGABRT: abort
PC=0x7fff6b33f33a m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4e54e60, 0xc000669920, 0xc000669980)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc0006698f0 sp=0xc0006698b8 pc=0x4005e0b
github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowBufferSubData(0x7fff3b04291a, 0xc000008a11, 0x0, 0x40, 0xc01f1db540)
	_cgo_gotypes.go:3574 +0x45 fp=0xc000669920 sp=0xc0006698f0 pc=0x4dec265
github.com/go-gl/gl/v3.3-core/gl.BufferSubData.func1(0x8a11, 0x0, 0x40, 0xc01f1db540)
	/Users/oreilly/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:8644 +0x7f fp=0xc000669960 sp=0xc000669920 pc=0x4e0df8f
github.com/go-gl/gl/v3.3-core/gl.BufferSubData(0x8a11, 0x0, 0x40, 0xc01f1db540)
	/Users/oreilly/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:8644 +0x47 fp=0xc000669990 sp=0xc000669960 pc=0x4df0b27
github.com/goki/gi/oswin/driver/internal/glgpu.(*Uniform).SetValueImpl(0xc0002fd2d0, 0x4f9a780, 0xc01f1db500, 0x400d2b2, 0xc01f1db500)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/internal/glgpu/uniforms.go:202 +0x26b5 fp=0xc000669b18 sp=0xc000669990 pc=0x4e26565
github.com/goki/gi/oswin/driver/internal/glgpu.(*Uniform).SetValue(0xc0002fd2d0, 0x4f9a780, 0xc01f1db500, 0xc01f1db500, 0xc0002fd2d0)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/internal/glgpu/uniforms.go:102 +0x43 fp=0xc000669b70 sp=0xc000669b18 pc=0x4e23e23
github.com/goki/gi/gi3d.(*Renderers).SetMatrix(0xc000239f68, 0xc01b752168)
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/render.go:79 +0xfb fp=0xc000669bd8 sp=0xc000669b70 pc=0x4daf64b
github.com/goki/gi/gi3d.(*Solid).Render3D(0xc01b752000, 0xc000239800, 0x1, 0x54251c0, 0xc000af8e20)
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/solid.go:206 +0xb6 fp=0xc000669c10 sp=0xc000669bd8 pc=0x4dbc386
github.com/goki/gi/gi3d.(*Scene).Render3D(0xc000239800, 0xc000239801)
	/Users/oreilly/go/src/github.com/goki/gi/gi3d/scene.go:1240 +0x36e fp=0xc000669e30 sp=0xc000669c10 pc=0x4db8a5e
github.com/goki/gi/gi3d.(*Scene).RenderOffFrame.func1()
```

**Comment by rcoreilly** [comment]
this was a memory leak etc -- fixed
