### ISSUE TITLE
marbles has new path errs

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#458]
must be due to updates in rasterx - need to add some checking?

```
panic: AddTo: bad path

goroutine 83 [running]:
github.com/srwiley/rasterx.Path.AddTo({0x14002810000, 0x3e7, 0x1400}, {0x101c53f58, 0x140031d0b40})
	/Users/oreilly/go/src/github.com/srwiley/rasterx/geomx.go:147 +0x274
github.com/goki/gi/girl.(*Paint).fill(0x14000eeebe0, 0x140008fc488)
	/Users/oreilly/go/src/github.com/goki/gi/girl/paint.go:301 +0x144
github.com/goki/gi/girl.(*Paint).FillPreserve(...)
	/Users/oreilly/go/src/github.com/goki/gi/girl/paint.go:339
github.com/goki/gi/girl.(*Paint).FillStrokeClear(0x14000eeebe0, 0x140008fc488)
	/Users/oreilly/go/src/github.com/goki/gi/girl/paint.go:62 +0x3c
github.com/goki/gi/svg.(*Circle).Render2D(0x14000eeea80)
	/Users/oreilly/go/src/github.com/goki/gi/svg/circle.go:63 +0x80
github.com/goki/gi/gi.(*Node2DBase).Render2DChildren(0x140008dca80)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:909 +0x8c
github.com/goki/gi/svg.(*Group).Render2D(0x140008dca80)
	/Users/oreilly/go/src/github.com/goki/gi/svg/group.go:70 +0x100
github.com/goki/gi/gi.(*Node2DBase).Render2DChildren(0x140008fc000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:909 +0x8c
github.com/goki/gi/svg.(*SVG).Render2D(0x140008fc000)
	/Users/oreilly/go/src/github.com/goki/gi/svg/svg.go:230 +0x140
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0x140008fc000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:870 +0x8c
github.com/goki/gi/gi.(*WidgetBase).ReRender2DTree(0x140008fc000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/widget.go:532 +0x1f8
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0x140008fc000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:842 +0x610
github.com/goki/gi/gi.(*Viewport2D).SetNeedsFullRender(0x140008fc000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:800 +0x144
main.UpdateMarbles()
	/Users/oreilly/go/src/github.com/goki/gi/examples/marbles/graph.go:397 +0xd8
main.RunMarbles()
	/Users/oreilly/go/src/github.com/goki/gi/examples/marbles/graph.go:478 +0x54
created by main.(*Graph).Run
	/Users/oreilly/go/src/github.com/goki/gi/examples/marbles/graph.go:127 +0x30

/Users/oreilly/go/src/github.com/goki/gi/examples/marbles/marbles <b>failed</b> at: Wed Mar  23 12:51:08 PDT 2022 with error: exit status 2
```

**Comment by rohrlich** [comment]
I did a git pull, go mod tidy and go mod vendor this morning and no build errors.

**Comment by rcoreilly** [comment]
these are rendering paths.. svg is not locking the rs prior to drawing!  path now has but need to add to all.
