### ISSUE TITLE
Crashed while just hovering over README link (or very near) in the widget playpen window

### ISSUE THREAD

**Issue by thazy** [goki/gi#47]
thazy@macbookpro ~/go/src/github.com/goki/gi/examples/widgets$ ./widgets
Received button signal: ButtonPressed from button: button2
Received button signal: ButtonReleased from button: button2
Received button signal: ButtonClicked from button: button2
panic: runtime error: index out of range

goroutine 122 [running]:
github.com/goki/gi.(*SpanRender).FindWrapPosLR(0xc42d25da40, 0x44a86f00441aa000, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/text.go:395 +0x2cb
github.com/goki/gi.(*TextRender).LayoutStdLR(0xc429869840, 0xc429868f60, 0xc429868ed8, 0xc429868fe8, 0xc1ac0000441aa000, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/text.go:1327 +0x3d8
github.com/goki/gi.(*Label).Style2D(0xc429868c80)
	/Users/thazy/go/src/github.com/goki/gi/label.go:173 +0x442
github.com/goki/gi.(*Node2DBase).Style2DTree.func1(0x461b820, 0xc429868c80, 0x1, 0x459aec0, 0xc429709400, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:469 +0x51
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc429868c80, 0x1, 0x459aec0, 0xc429709400, 0x45cf548, 0xc42d743500)
	/Users/thazy/go/src/github.com/goki/ki/node.go:998 +0x6b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc429709400, 0x1, 0x459aec0, 0xc429709400, 0x45cf548, 0xc42d743501)
	/Users/thazy/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/gi.(*Node2DBase).Style2DTree(0xc429709400)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:464 +0x82
github.com/goki/gi.PopupTooltip(0xc42ebc49b0, 0x41, 0x46d, 0x1a9, 0xc42042aa80, 0x45afcf3, 0x5, 0x18)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:463 +0x55c
github.com/goki/gi.(*Label).LabelEvents.func1(0x461b820, 0xc42016b900, 0x461f960, 0xc420424000, 0x5, 0x45410a0, 0xc42dc2e1b0)
	/Users/thazy/go/src/github.com/goki/gi/label.go:220 +0x210
github.com/goki/gi.(*WinEventRecv).Call(0xc420748eb0, 0x461f960, 0xc420424000, 0x5, 0x45410a0, 0xc42dc2e1b0)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1081 +0x6d
github.com/goki/gi.(*Window).SendEventSignal(0xc420424000, 0x4614a80, 0xc42dc2e1b0, 0xc428e96101)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1195 +0xc65
github.com/goki/gi.(*Window).SendHoverEvent(0xc420424000, 0xc42b9dd1a0)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1277 +0xaf
github.com/goki/gi.(*Window).EventLoop.func2()
	/Users/thazy/go/src/github.com/goki/gi/window.go:883 +0x5a
created by time.goFunc
	/usr/local/Cellar/go/1.10.3/libexec/src/time/sleep.go:172 +0x44
thazy@macbookpro ~/go/src/github.com/goki/gi/examples/widgets$

**Comment by rcoreilly** [comment]
Tom -- I fixed this crash already -- can you make sure you've done "git pull" in goki/gi to get the latest code, then build again?  Thanks a ton for all the great bug reports!! :)

**Comment by rcoreilly** [comment]
was able to reproduce and just checked in a fix -- more than one way to crash!
