### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#477]
still getting crashes like this on mac..

```
cd /Users/oreilly/go/src/github.com/emer/axon/examples/ra25 (from: {FileDirPath})
NThreads: 1	go max procs: 10	num cpu:10
2022-06-13 18:11:13.331 ra25[82621:5867693] *** Assertion failure in -[_NSMenuShortcutUpdater schedule:], NSMenuItem.m:4354
2022-06-13 18:11:13.333 ra25[82621:5867693] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Menu should have been unscheduled for updating'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018af85198 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x000000018accfe04 objc_exception_throw + 60
	2   Foundation                          0x000000018bebbea8 -[NSCalendarDate initWithCoder:] + 0
	3   CoreFoundation                      0x000000018af04af4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
	4   CoreFoundation                      0x000000018af0496c __CFRunLoopDoBlocks + 412
	5   CoreFoundation                      0x000000018af0397c __CFRunLoopRun + 1720
	6   CoreFoundation                      0x000000018af02b24 CFRunLoopRunSpecific + 600
	7   HIToolbox                           0x0000000193b3b338 RunCurrentEventLoopInMode + 292
	8   HIToolbox                           0x0000000193b3b0b4 ReceiveNextEventCommon + 564
	9   HIToolbox                           0x0000000193b3ae68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
	10  AppKit                              0x000000018da6978c _DPSNextEvent + 860
	11  AppKit                              0x000000018da68084 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
	12  ra25                                0x00000001031cfeec _glfwPlatformWaitEventsTimeout + 132
	13  ra25                                0x00000001025fc97c runtime.asmcgocall.abi0 + 124
)
libc++abi: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x18ae02d98 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1031d2c2c, 0x14000073e68)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/cgocall.go:157 +0x54 fp=0x14000073e30 sp=0x14000073df0 pc=0x10259c3e4
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEventsTimeout(0x3fc999999999999a)
	_cgo_gotypes.go:2442 +0x38 fp=0x14000073e60 sp=0x14000073e30 pc=0x10311ff58
github.com/go-gl/glfw/v3.3/glfw.WaitEventsTimeout(0x14000073ed8?)
	/Users/oreilly/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:1009 +0x24 fp=0x14000073e80 sp=0x14000073e60 pc=0x103128c54
github.com/goki/gi/oswin/driver/vkos.(*appImpl).mainLoop(0x104c77e20)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:162 +0x128 fp=0x14000073f00 sp=0x14000073e80 pc=0x10312ae08
github.com/goki/gi/oswin/driver/vkos.Main(0x14000111f48?)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:79 +0xc4 fp=0x14000073f20 sp=0x14000073f00 pc=0x10312a8f4
github.com/goki/gi/oswin/driver.driverMain(...)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/driver_vkos.go:18
github.com/goki/gi/oswin/driver.Main(...)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/driver.go:27
github.com/goki/gi/gimain.Main(0x1038831c0?)
	/Users/oreilly/go/src/github.com/goki/gi/gimain/gimain.go:31 +0x68 fp=0x14000073f50 sp=0x14000073f20 pc=0x1031b04f8
main.main()
	/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25.go:46 +0x64 fp=0x14000073f70 sp=0x14000073f50 pc=0x1031b0714
runtime.main()
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250 +0x250 fp=0x14000073fd0 sp=0x14000073f70 pc=0x1025ce9c0
runtime.goexit()
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/asm_arm64.s:1259 +0x4 fp=0x14000073fd0 sp=0x14000073fd0 pc=0x1025fcb54

goroutine 9 [chan receive]:
github.com/emer/axon/axon.(*NetworkBase).ThrWorker(0x140002a6700, 0x0)
	/Users/oreilly/go/src/github.com/emer/axon/axon/networkbase.go:687 +0x80
created by github.com/emer/axon/axon.(*NetworkBase).StartThreads
	/Users/oreilly/go/src/github.com/emer/axon/axon/networkbase.go:671 +0xdc

goroutine 10 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0x1400062e098, 0x2c)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/sema.go:513 +0x170
sync.(*Cond).Wait(0x1400062e088)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/sync/cond.go:56 +0xd8
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0x1400062e080)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x68
github.com/goki/gi/oswin/driver/vkos.(*windowImpl).NextEvent(0x140004ce000?)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/window.go:152 +0x28
github.com/goki/gi/gi.(*Window).EventLoop(0x140004ce000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1541 +0x60
github.com/goki/gi/gi.(*Window).StartEventLoop(0x104caea00?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:897 +0xb8
main.guirun()
	/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25.go:55 +0x38
main.main.func1()
	/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25.go:47 +0x20
github.com/goki/gi/gimain.Main.func1({0x0?, 0x0?})
	/Users/oreilly/go/src/github.com/goki/gi/gimain/gimain.go:32 +0x28
github.com/goki/gi/oswin/driver/vkos.Main.func1()
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:76 +0x44
created by github.com/goki/gi/oswin/driver/vkos.Main
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:75 +0xb4

goroutine 16 [select]:
github.com/goki/gi/oswin/driver/vkos.(*windowImpl).winLoop(0x1400062e000)
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/window.go:161 +0x88
created by github.com/goki/gi/oswin/driver/vkos.(*appImpl).NewWindow
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:286 +0xb14

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x18adf60f5
r5      0x16d86aa20
r6      0x6e
r7      0x600
r8      0xd1bb7a97bc9a2bba
r9      0xd1bb7a96b9d22e3a
r10     0x200
r11     0xb
r12     0xb
r13     0x18b3462ed
r14     0x18adf611b
r15     0x0
r16     0x148
r17     0x1e4ec3680
r18     0x0
r19     0x6
r20     0x105480580
r21     0x103
r22     0x105480660
r23     0x6000039e01b0
r24     0x0
r25     0x1
r26     0x0
r27     0x1e3804000
r28     0x1
r29     0x16d86a990
lr      0x18ae37ee0
sp      0x16d86a970
pc      0x18ae02d98
fault   0x18ae02d98

/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25 <b>failed</b> at: Mon Jun  13 18:11:13 PDT 2022 with error: exit status 2

**Comment by rcoreilly** [comment]
tried moving the "set" calls to the end here:
```C
MenuDelegate* newMainMenu(NSWindow* view) {
	NSMenu* mm = [[NSMenu alloc] init];
	MenuDelegate* md = [[MenuDelegate alloc] init];
	[md retain];
	[mm retain];
 	[mm setAutoenablesItems:NO];
	uintptr_t sm = doAddSubMenu((uintptr_t)mm, "app");
	doAddMenuItem((uintptr_t)view, sm, (uintptr_t)md, "app", "", false, false, false, false, 0, false);
 	[md setMainMenu: mm];
	[md setView: view];
	return md;
}
```

**Comment by rcoreilly** [comment]
but this did not fix the issue.

**Comment by rcoreilly** [comment]
bunch of random experimentation resulted in a fix: set the main menu right away..

**Comment by rcoreilly** [comment]
Alan confirmed it seems to be fixed!
