### ISSUE TITLE
Support arbitrarily ordered elements in grid layouts

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#611]
For example, having child 0 be at the end of the grid, after other elements. It is triggering index out of range panics:

```
panic: runtime error: index out of range [4] with length 4

goroutine 11 [running]:
github.com/goki/gi/gi.GatherSizesGrid(0xc000f71100)
        C:/Users/korei/goki/gi/gi/layout_impl.go:345 +0xe66
github.com/goki/gi/gi.(*Layout).Size2D(0xc000f71100, 0xc000f71100?)
        C:/Users/korei/goki/gi/gi/layout.go:1216 +0x55
github.com/goki/gi/gi.(*Node2DBase).Size2DTree.func2({0x7ff7b352e4d0?, 0xc000f71100?}, 0x7ff7b11e2fae?, {0x7ff7b1f74da0?, 0xc0054c58f8?})
        C:/Users/korei/goki/gi/gi/node2d.go:816 +0x70
github.com/goki/ki/ki.(*Node).FuncDownMeLast(0xc000f36000, 0x0, {0x7ff7b205c960, 0xc000f36000}, 0x7ff7b339f830, 0xc0054c5a60)
        C:/Users/korei/goki/ki/ki/node.go:1287 +0x7cb
github.com/goki/gi/gi.(*Node2DBase).Size2DTree(0xc000f36000, 0x0)
        C:/Users/korei/goki/gi/gi/node2d.go:800 +0xea
github.com/goki/gi/gi.(*Node2DBase).FullRender2DTree(0xc000f36000)
        C:/Users/korei/goki/gi/gi/node2d.go:723 +0x49
github.com/goki/gi/gi.(*Viewport2D).FullRender2DTree(0xc000f36000?)
        C:/Users/korei/goki/gi/gi/viewport.go:624 +0xd4
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0xc000f36000)
        C:/Users/korei/goki/gi/gi/viewport.go:898 +0x537
github.com/goki/gi/gi.(*Viewport2D).SetNeedsFullRender(0xc000f36000?)
        C:/Users/korei/goki/gi/gi/viewport.go:858 +0x78
github.com/goki/gi/gi.(*Window).FullReRender(0xc000eeb900)
        C:/Users/korei/goki/gi/gi/window.go:1055 +0x9c
github.com/goki/gi/gi.(*Window).Resized(0xc000eeb900, {0x7ff700000004?, 0x9?})
        C:/Users/korei/goki/gi/gi/window.go:826 +0x3c5
github.com/goki/gi/gi.(*Window).HiPriorityEvents(0xc000eeb900, {0x7ff7b351e528?, 0xc000b0a000?})
        C:/Users/korei/goki/gi/gi/window.go:1862 +0x706
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000eeb900, {0x7ff7b351e528, 0xc000b0a000})
        C:/Users/korei/goki/gi/gi/window.go:1693 +0x578
github.com/goki/gi/gi.(*Window).EventLoop(0xc000eeb900)
        C:/Users/korei/goki/gi/gi/window.go:1631 +0x33
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000eeb900?)
        C:/Users/korei/goki/gi/gi/window.go:995 +0x57
main.mainrun()
        C:/Users/korei/goki/gi/examples/demo/demo.go:52 +0x1a5
github.com/goki/gi/gimain.Main.func1({0xc00011bfa6?, 0xc00011bfb8?})
        C:/Users/korei/goki/gi/gimain/gimain.go:32 +0x1b
github.com/goki/gi/oswin/driver/vkos.Main.func1()
        C:/Users/korei/goki/gi/oswin/driver/vkos/app.go:78 +0x2e
created by github.com/goki/gi/oswin/driver/vkos.Main
        C:/Users/korei/goki/gi/oswin/driver/vkos/app.go:77 +0x85
```

**Comment by kkoreilly** [comment]
Will not do. This is a violation of basic logical and semantic principles and is likely bad for accessibility. Grid elements should be ordered as you want them to appear.
