### ISSUE TITLE
Crash in close window -- need goosi.Window lock.

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#630]
Can still get a crash when Paint is drawing and the window is being closed.  Need to coordinate these with mutex.  Tried adding the global win.mu mutex to send paint event, but that ends up being in a different thread due to GoStartEventLoop, so the paint event sending returns immediately.  Probably just need to expose the window mutex on goosi.Window.

```
SIGILL: illegal instruction
PC=0x10269c57c m=5 sigcode=2
signal arrived during cgo execution
instruction bytes: 0x32 0x35 0x4d 0x56 0x4b 0x52 0x65 0x66 0x65 0x72 0x65 0x6e 0x63 0x65 0x43 0x6f

goroutine 40 [syscall]:
runtime.cgocall(0x10059e224, 0x1400050b9d8)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/cgocall.go:157 +0x44 fp=0x1400050b990 sp=0x1400050b950 pc=0x1001230c4
github.com/goki/vulkan._Cfunc_callVkQueueSubmit(0x600003044e88, 0x1, 0x6000024e0730, 0x6000036452c0)
	_cgo_gotypes.go:9683 +0x34 fp=0x1400050b9d0 sp=0x1400050b990 pc=0x1003911b4
github.com/goki/vulkan.QueueSubmit.func1(0x600003044e88, 0x1?, 0x10059d814?, 0x6000036452c0)
	/Users/oreilly/go/src/goki.dev/vulkan/vulkan.go:176 +0xb4 fp=0x1400050ba30 sp=0x1400050b9d0 pc=0x1003b28e4
github.com/goki/vulkan.QueueSubmit(0x600003044e88, 0x32000?, {0x1400050bba8?, 0x1, 0x1400050bbb8?}, 0x6000036452c0)
	/Users/oreilly/go/src/goki.dev/vulkan/vulkan.go:176 +0x68 fp=0x1400050bb50 sp=0x1400050ba30 pc=0x1003b2688
goki.dev/vgpu/v2/vgpu.(*Surface).SubmitRender(0x140001e0840, 0x149649618)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/surface.go:364 +0x118 fp=0x1400050bc50 sp=0x1400050bb50 pc=0x1003e15e8
goki.dev/vgpu/v2/vdraw.(*Drawer).EndDraw(0x140001f76a0)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vdraw/draw.go:266 +0xb8 fp=0x1400050bc90 sp=0x1400050bc50 pc=0x1003fd698
goki.dev/gi/v2/gi.(*RenderWin).DrawScenes(0x140001c4b00)
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/winrender.go:236 +0x14c fp=0x1400050bd30 sp=0x1400050bc90 pc=0x10054d44c
goki.dev/gi/v2/gi.(*RenderWin).RenderWindow(0x140001c4b00)
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/winrender.go:208 +0x98 fp=0x1400050bda0 sp=0x1400050bd30 pc=0x10054d208
goki.dev/gi/v2/gi.(*RenderWin).HandleWindowEvents(0x140001c4b00, {0x100c36118, 0x14007e93b20})
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:726 +0x444 fp=0x1400050be90 sp=0x1400050bda0 pc=0x100533094
goki.dev/gi/v2/gi.(*RenderWin).HandleEvent(0x140001c4b00, {0x100c36118, 0x14007e93b20})
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:711 +0x134 fp=0x1400050bf10 sp=0x1400050be90 pc=0x100532b74
goki.dev/gi/v2/gi.(*RenderWin).EventLoop(0x140001c4b00)
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:682 +0x50 fp=0x1400050bfb0 sp=0x1400050bf10 pc=0x100532830
goki.dev/gi/v2/gi.(*RenderWin).GoStartEventLoop.func1()
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:604 +0x28 fp=0x1400050bfd0 sp=0x1400050bfb0 pc=0x1005326d8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400050bfd0 sp=0x1400050bfd0 pc=0x100185c04
created by goki.dev/gi/v2/gi.(*RenderWin).GoStartEventLoop in goroutine 10
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:604 +0xa4

goroutine 1 [runnable, locked to thread]:
runtime.gcTrigger.test({0x0?, 0x0?, 0x0?})
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:569 +0x144 fp=0x140000569f0 sp=0x140000569f0 pc=0x1001381b4
runtime.mallocgc(0x8, 0x100b18520, 0x0)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/malloc.go:1241 +0x78c fp=0x14000056a60 sp=0x140000569f0 pc=0x10012bb3c
runtime.convT64(0x14989de18)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/iface.go:383 +0x48 fp=0x14000056a90 sp=0x14000056a60 pc=0x100129508
github.com/goki/vulkan.DestroySampler.func1(0x14989de18, 0x600003045ce0, 0x8?)
	/Users/oreilly/go/src/goki.dev/vulkan/vulkan.go:706 +0x34 fp=0x14000056ae0 sp=0x14000056a90 pc=0x1003b5a34
github.com/goki/vulkan.DestroySampler(0x14989de18, 0x600003045ce0, 0x14989de18?)
	/Users/oreilly/go/src/goki.dev/vulkan/vulkan.go:706 +0x2c fp=0x14000056b10 sp=0x14000056ae0 pc=0x1003b59cc
goki.dev/vgpu/v2/vgpu.(*Sampler).Destroy(...)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/texture.go:91
goki.dev/vgpu/v2/vgpu.(*Texture).Destroy(0x140000a4000)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/texture.go:25 +0x40 fp=0x14000056b40 sp=0x14000056b10 pc=0x1003e2490
goki.dev/vgpu/v2/vgpu.(*Val).Free(...)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/vals.go:147
goki.dev/vgpu/v2/vgpu.(*Vals).Free(0x100b40a40?)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/vals.go:410 +0x90 fp=0x14000056b70 sp=0x14000056b40 pc=0x1003e37d0
goki.dev/vgpu/v2/vgpu.(*Vars).Free(0x140001f7758, 0x140000923c0)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/vars.go:744 +0x138 fp=0x14000056bd0 sp=0x14000056b70 pc=0x1003e6288
goki.dev/vgpu/v2/vgpu.(*Memory).FreeBuff(0x140001f7728, 0x498aa800?)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/memory.go:250 +0x6c fp=0x14000056c20 sp=0x14000056bd0 pc=0x1003db96c
goki.dev/vgpu/v2/vgpu.(*Memory).Free(0x140001f7728)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/memory.go:227 +0xb0 fp=0x14000056c70 sp=0x14000056c20 pc=0x1003db8c0
goki.dev/vgpu/v2/vgpu.(*Memory).Destroy(0x140001f7728, 0x1498aa800?)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/memory.go:88 +0x24 fp=0x14000056ca0 sp=0x14000056c70 pc=0x1003dad54
goki.dev/vgpu/v2/vgpu.(*System).Destroy(0x140001f76a0)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vgpu/system.go:124 +0x250 fp=0x14000056e00 sp=0x14000056ca0 pc=0x1003e1c00
goki.dev/vgpu/v2/vdraw.(*Drawer).Destroy(0x140001f76a0)
	/Users/oreilly/go/src/goki.dev/vgpu/v2/vdraw/vdraw.go:83 +0x24 fp=0x14000056e20 sp=0x14000056e00 pc=0x1003fd8e4
goki.dev/goosi/driver/desktop.(*windowImpl).Close.func1()
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/window.go:409 +0x4c fp=0x14000056e40 sp=0x14000056e20 pc=0x100592eec
goki.dev/goosi/driver/desktop.(*appImpl).mainLoop(0x10128c420)
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/app.go:157 +0xf4 fp=0x14000056ec0 sp=0x14000056e40 pc=0x10058d854
goki.dev/goosi/driver/desktop.Main(0x14000044728?)
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/app.go:79 +0xa4 fp=0x14000056ee0 sp=0x14000056ec0 pc=0x10058d684
goki.dev/goosi/driver.driverMain(...)
	/Users/oreilly/go/src/goki.dev/goosi/driver/driver_desktop.go:20
goki.dev/goosi/driver.Main(...)
	/Users/oreilly/go/src/goki.dev/goosi/driver/driver.go:27
goki.dev/gi/v2/gimain.Main(0x100c29fb0)
	/Users/oreilly/go/src/goki.dev/gi/v2/gimain/gimain.go:31 +0x60 fp=0x14000056f10 sp=0x14000056ee0 pc=0x10059af10
main.main()
	/Users/oreilly/go/src/goki.dev/gi/v2/examples/widgets/widgets.go:20 +0x24 fp=0x14000056f30 sp=0x14000056f10 pc=0x10059b084
runtime.main()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:267 +0x2bc fp=0x14000056fd0 sp=0x14000056f30 pc=0x100155f7c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000056fd0 sp=0x14000056fd0 pc=0x100185c04

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000044f90 sp=0x14000044f70 pc=0x1001563a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.forcegchelper()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:322 +0xb8 fp=0x14000044fd0 sp=0x14000044f90 pc=0x100156238
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000044fd0 sp=0x14000044fd0 pc=0x100185c04
created by runtime.init.6 in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:310 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000045760 sp=0x14000045740 pc=0x1001563a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgcsweep.go:321 +0x108 fp=0x140000457b0 sp=0x14000045760 pc=0x100143298
runtime.gcenable.func1()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:200 +0x28 fp=0x140000457d0 sp=0x140000457b0 pc=0x100137f88
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000457d0 sp=0x140000457d0 pc=0x100185c04
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1400006c000?, 0x100aaae80?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000045f50 sp=0x14000045f30 pc=0x1001563a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1012ba880)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgcscavenge.go:425 +0x5c fp=0x14000045f80 sp=0x14000045f50 pc=0x100140a9c
runtime.bgscavenge(0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgcscavenge.go:658 +0xac fp=0x14000045fb0 sp=0x14000045f80 pc=0x10014105c
runtime.gcenable.func2()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:201 +0x28 fp=0x14000045fd0 sp=0x14000045fb0 pc=0x100137f28
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000045fd0 sp=0x14000045fd0 pc=0x100185c04
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:201 +0xac

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x14000366be0?, 0x40?, 0x22?, 0x1000000010?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000054d80 sp=0x14000054d60 pc=0x1001563a8
runtime.runfinq()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mfinal.go:193 +0x108 fp=0x14000054fd0 sp=0x14000054d80 pc=0x100137078
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000054fd0 sp=0x14000054fd0 pc=0x100185c04
created by runtime.createfing in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mfinal.go:163 +0x80

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000040730 sp=0x14000040710 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x140000407d0 sp=0x14000040730 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000407d0 sp=0x140000407d0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000046730 sp=0x14000046710 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x140000467d0 sp=0x14000046730 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000467d0 sp=0x140000467d0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x70784bf22d5e5?, 0x1?, 0xa0?, 0xf1?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000040f30 sp=0x14000040f10 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x14000040fd0 sp=0x14000040f30 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000040fd0 sp=0x14000040fd0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x1012f1000?, 0x3?, 0xa8?, 0xbe?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000046f30 sp=0x14000046f10 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x14000046fd0 sp=0x14000046f30 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000046fd0 sp=0x14000046fd0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x70784bf22e461?, 0x1?, 0x88?, 0x89?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000047730 sp=0x14000047710 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x140000477d0 sp=0x14000047730 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000477d0 sp=0x140000477d0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x70784bf22dc14?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000041730 sp=0x14000041710 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x140000417d0 sp=0x14000041730 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000417d0 sp=0x140000417d0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x70784bf22d6df?, 0x1?, 0x6d?, 0xc2?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000047f30 sp=0x14000047f10 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x14000047fd0 sp=0x14000047f30 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000047fd0 sp=0x14000047fd0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x70784bf22d8d3?, 0x1?, 0x45?, 0xb7?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000041f30 sp=0x14000041f10 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x14000041fd0 sp=0x14000041f30 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000041fd0 sp=0x14000041fd0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x70784bf22ed02?, 0x1?, 0x1c?, 0x82?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000504730 sp=0x14000504710 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x140005047d0 sp=0x14000504730 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140005047d0 sp=0x140005047d0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x70784bf23838f?, 0x3?, 0x87?, 0xa5?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000042730 sp=0x14000042710 pc=0x1001563a8
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1293 +0xd8 fp=0x140000427d0 sp=0x14000042730 pc=0x100139948
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000427d0 sp=0x140000427d0 pc=0x100185c04
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/mgc.go:1217 +0x28

goroutine 10 [semacquire]:
runtime.gopark(0x1012bf740?, 0x100aaae88?, 0x20?, 0x2d?, 0x10053c614?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000055d60 sp=0x14000055d40 pc=0x1001563a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:404
runtime.semacquire1(0x1012f0768, 0x20?, 0x1, 0x0, 0x1?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/sema.go:160 +0x208 fp=0x14000055db0 sp=0x14000055d60 pc=0x100167988
sync.runtime_Semacquire(0x1400025e120?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/sema.go:62 +0x2c fp=0x14000055df0 sp=0x14000055db0 pc=0x10018196c
sync.(*WaitGroup).Wait(0x1012f0760)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/sync/waitgroup.go:116 +0x74 fp=0x14000055e10 sp=0x14000055df0 pc=0x10019d764
goki.dev/gi/v2/gi.Wait(...)
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:34
goki.dev/gi/v2/gi.(*StageBase).Wait(...)
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/stage.go:439
goki.dev/gi/v2/gi.(*MainStage).Wait(0x1400025e120)
	<autogenerated>:1 +0x38 fp=0x14000055e30 sp=0x14000055e10 pc=0x100567f58
main.mainrun()
	/Users/oreilly/go/src/goki.dev/gi/v2/examples/widgets/widgets.go:363 +0xe94 fp=0x14000055f90 sp=0x14000055e30 pc=0x10059bf34
goki.dev/gi/v2/gimain.Main.func1({0x0?, 0x0?})
	/Users/oreilly/go/src/goki.dev/gi/v2/gimain/gimain.go:33 +0x30 fp=0x14000055fb0 sp=0x14000055f90 pc=0x10059af60
goki.dev/goosi/driver/desktop.Main.func1()
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/app.go:76 +0x38 fp=0x14000055fd0 sp=0x14000055fb0 pc=0x1005954f8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000055fd0 sp=0x14000055fd0 pc=0x100185c04
created by goki.dev/goosi/driver/desktop.Main in goroutine 1
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/app.go:75 +0x98

goroutine 25 [chan receive]:
runtime.gopark(0x14000070180?, 0x0?, 0x0?, 0x0?, 0x14000266048?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000327ed0 sp=0x14000327eb0 pc=0x1001563a8
runtime.chanrecv(0x140003b2660, 0x0, 0x1)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/chan.go:583 +0x414 fp=0x14000327f50 sp=0x14000327ed0 pc=0x1001253c4
runtime.chanrecv1(0x14000580000?, 0x100185c08?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/chan.go:442 +0x14 fp=0x14000327f80 sp=0x14000327f50 pc=0x100124fa4
goki.dev/gi/v2/gi.TextFieldBlink()
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/textfield.go:864 +0xf8 fp=0x14000327fd0 sp=0x14000327f80 pc=0x100545138
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000327fd0 sp=0x14000327fd0 pc=0x100185c04
created by goki.dev/gi/v2/gi.(*TextField).StartCursor in goroutine 40
	/Users/oreilly/go/src/goki.dev/gi/v2/gi/textfield.go:912 +0x150

goroutine 82 [runnable]:
runtime.gopark(0x1005b14b0?, 0x140037cfee8?, 0x0?, 0x0?, 0x10001ed08?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:398 +0xc8 fp=0x140037cfe70 sp=0x140037cfe50 pc=0x1001563a8
runtime.chansend(0x14000110360, 0x140037cff38, 0x1, 0x1400004b200?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/chan.go:259 +0x3c4 fp=0x140037cfee0 sp=0x140037cfe70 pc=0x100124644
runtime.chansend1(0x140037cff48?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/chan.go:145 +0x18 fp=0x140037cff10 sp=0x140037cfee0 pc=0x100124268
goki.dev/goosi/driver/desktop.(*appImpl).RunOnMain(0x10128c420, 0x14007d233d0)
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/app.go:94 +0x64 fp=0x140037cff50 sp=0x140037cff10 pc=0x10058d714
goki.dev/goosi/driver/desktop.(*windowImpl).Close(0x140001f7500)
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/window.go:404 +0x120 fp=0x140037cff90 sp=0x140037cff50 pc=0x100592e10
goki.dev/goosi/driver/desktop.(*windowImpl).CloseReq(0x0?)
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/window.go:386 +0x58 fp=0x140037cffb0 sp=0x140037cff90 pc=0x100592cc8
goki.dev/goosi/driver/desktop.(*windowImpl).closeReq.func1()
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/window.go:561 +0x28 fp=0x140037cffd0 sp=0x140037cffb0 pc=0x100593aa8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140037cffd0 sp=0x140037cffd0 pc=0x100185c04
created by goki.dev/goosi/driver/desktop.(*windowImpl).closeReq in goroutine 1
	/Users/oreilly/go/src/goki.dev/goosi/driver/desktop/window.go:561 +0x5c

r0      0x14a059400
r1      0x171e18d20
r2      0x2
r3      0x171e19890
r4      0x600003c41ed0
r5      0x171e18b20
r6      0x0
r7      0x0
r8      0x10269c57c
r9      0x0
r10     0x0
r11     0xfffffffffffffff0
r12     0xf
r13     0x10
r14     0x600003b58900
r15     0x10
r16     0x1998ac2b0
r17     0x0
r18     0x0
r19     0x171e18d78
r20     0x171e18d20
r21     0x171e1a7f0
r22     0x14a059400
r23     0x0
r24     0x60000051bdd0
r25     0x0
r26     0x1
r27     0x0
r28     0x0
r29     0x171e18aa0
lr      0x102368c88
sp      0x171e18a90
pc      0x10269c57c
fault   0x10269c57c

/Users/oreilly/go/src/goki.dev/gi/v2/examples/widgets/widgets <b>failed</b> at: Mon Oct  2 10:54:45 PDT 2023 with error: exit status 2
```

**Comment by rcoreilly** [comment]
added a Lock() method with bool return that checks if window has been closed already, and returns false if so -- should do the trick.
