### ISSUE TITLE
Example fails to run with "Grow undefined (type *styles.Style has no field or method"

### ISSUE THREAD

**Issue by ReubenBTalbott** [goki/gi#643]
This is on my 2023 MacBook Pro, Go version 1.21.4,  I installed the Vulcan drivers with all options

I searched around and couldn't find anyone having the same issue

Here is the full error: 
```
reuben@ThinBoy:~/git/gi/examples/widgets$ go build
# goki.dev/gi/v2/gi
../../gi/button.go:174:6: s.Grow undefined (type *styles.Style has no field or method Grow)
../../gi/button.go:187:7: s.Gap undefined (type *styles.Style has no field or method Gap)
../../gi/button.go:191:7: s.Min undefined (type *styles.Style has no field or method Min)
../../gi/button.go:192:7: s.Min undefined (type *styles.Style has no field or method Min)
../../gi/button.go:195:7: s.Align undefined (type *styles.Style has no field or method Align)
../../gi/button.go:199:7: s.Min undefined (type *styles.Style has no field or method Min)
../../gi/button.go:200:7: s.Min undefined (type *styles.Style has no field or method Min)
../../gi/button.go:210:7: s.SetNonSelectable undefined (type *styles.Style has no field or method SetNonSelectable)
../../gi/button.go:211:7: s.SetTextWrap undefined (type *styles.Style has no field or method SetTextWrap)
../../gi/button.go:214:7: s.Max undefined (type *styles.Style has no field or method Max)
../../gi/button.go:214:7: too many errors
```

**Comment by kkoreilly** [comment]
Apologies for the issue. It should be fixed now if you pull the latest version of gi. There is currently some instability in the codebase due to an ongoing major redesign, but things should be more stable now, and the latest released version (currently v2.0.0-dev0.0.11) will always work. The documentation is currently out of date and will be significantly improved soon, and many tutorials and tests will be added. Currently, examples/demo provides the best demonstration of the features of the framework and how to write code with it.

**Comment by ReubenBTalbott** [comment]
It builds now but fails to run, I'll switch to latest

Here is the error if you're interested:
```
$ ./widgets
2023/11/14 15:50:56 ERROR open /Users/reuben/Library/GoGi/prefs.json: no such file or directory
[mvk-error] SPIR-V to MSL conversion error: Unsized array of descriptors requires argument buffer tier 2
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
panic: vulkan error: vulkan error: invalid shader (NV) (-1000012000)

goroutine 1 [running, locked to thread]:
goki.dev/vgpu/v2/vgpu.IfPanic(...)
	/Users/reuben/go/pkg/mod/goki.dev/vgpu/v2@v2.0.0-dev0.0.15/vgpu/errors.go:39
goki.dev/vgpu/v2/vgpu.(*Pipeline).Config(0x1400022a200)
	/Users/reuben/go/pkg/mod/goki.dev/vgpu/v2@v2.0.0-dev0.0.15/vgpu/pipeline.go:194 +0x4d4
goki.dev/vgpu/v2/vgpu.(*System).Config(0x140001d59a0)
	/Users/reuben/go/pkg/mod/goki.dev/vgpu/v2@v2.0.0-dev0.0.15/vgpu/system.go:277 +0xdc
goki.dev/vgpu/v2/vdraw.(*Drawer).ConfigSys(0x140001d59a0)
	/Users/reuben/go/pkg/mod/goki.dev/vgpu/v2@v2.0.0-dev0.0.15/vdraw/config.go:106 +0x7cc
goki.dev/vgpu/v2/vdraw.(*Drawer).ConfigSurface(0x140001d59a0, 0x14000318a50, 0x1400032a480?)
	/Users/reuben/go/pkg/mod/goki.dev/vgpu/v2@v2.0.0-dev0.0.15/vdraw/vdraw.go:51 +0x9c
goki.dev/goosi/driver/desktop.(*appImpl).NewWindow.func2()
	/Users/reuben/go/pkg/mod/goki.dev/goosi@v0.0.11/driver/desktop/app.go:250 +0x11c
goki.dev/goosi/driver/desktop.(*appImpl).mainLoop(0x10723ab20)
	/Users/reuben/go/pkg/mod/goki.dev/goosi@v0.0.11/driver/desktop/app.go:158 +0xf4
goki.dev/goosi/driver/desktop.Main(0x14000066728?)
	/Users/reuben/go/pkg/mod/goki.dev/goosi@v0.0.11/driver/desktop/app.go:80 +0xa4
goki.dev/goosi/driver.driverMain(...)
	/Users/reuben/go/pkg/mod/goki.dev/goosi@v0.0.11/driver/driver_desktop.go:20
goki.dev/goosi/driver.Main(...)
	/Users/reuben/go/pkg/mod/goki.dev/goosi@v0.0.11/driver/driver.go:27
goki.dev/gi/v2/gimain.Run(0x1069e5360)
	/Users/reuben/git/gi/gimain/gimain.go:26 +0x60
main.main()
	/Users/reuben/git/gi/examples/widgets/widgets.go:22 +0x24
	```

**Comment by ReubenBTalbott** [comment]
Same error when trying to run on latest

**Comment by rcoreilly** [comment]
This is a new bug with the recent vulkan drivers on mac -- if you grab 1.3.250 from here: https://vulkan.lunarg.com/sdk/home  it should work.

**Comment by rcoreilly** [comment]
Here's an updated ticket tracking this issue: https://github.com/goki/vgpu/issues/9
